<?php

namespace OnlineFashionBundle\Repository;

/**
 * CategoryParentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryParentRepository extends \Doctrine\ORM\EntityRepository
{
}
