<?php

namespace OnlineFashionBundle\Repository;

/**
 * OrderArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
