<?php

namespace OnlineFashionBundle\Repository;

/**
 * PromotionArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
